### ISSUE TITLE
Can we have only 2 posts ?

### ISSUE THREAD

**Issue by iamshm** [MarcusNg/flutter_instagram_feed_ui_redesign#1]
When I'm making a 3rd post by calling _buildpost(2), I'm getting error of not in range
i have updated the post.dart file for 3 posts

Also I'm not able to change name of the posts
Im a beginner in flutter

**Comment by MarcusNg** [comment]
You can have an unlimited number of posts. The not in range error means that you're trying to access a post at an index that does not exist. Make sure that you updated the posts array correctly

**Comment by iamshm** [comment]
I updated the post class to but the buildPost instance fails to call the next post from that post class.
Giving out the error I mentioned above

**Comment by iamshm** [comment]
And Dont you think it would be better to use listview builder for the posts ?
It would make the app smoother, I believe

**Comment by MarcusNg** [comment]
You have to **hot restart the app** to update the constant post data. A list view builder would be more optimal, which I use very often in future speed codes.

**Comment by iamshm** [comment]
Thanks for the reply !
